/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package General;

import Voters.*;
import Admin.*;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.*;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author welcome
 */
public class Instructions extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Instructions() {
        initComponents();
        JButton [] btns = {jButton1, jButton2, jButton3, jButton4, jButton5, jButton7, jButton13};
        for (JButton btn : btns) {
            btn.setBackground(new Color(21,25,28));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(54,81,207));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(21,25,28));
                }
                
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnRoot = new javax.swing.JPanel();
        pnSide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pnCenter = new javax.swing.JPanel();
        pnCBottom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pniCTop = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pniCCenter = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnRoot.setLayout(new java.awt.BorderLayout());

        pnSide.setBackground(new java.awt.Color(21, 25, 28));
        pnSide.setPreferredSize(new java.awt.Dimension(250, 0));

        jPanel1.setBackground(new java.awt.Color(21, 25, 28));
        jPanel1.setPreferredSize(new java.awt.Dimension(270, 150));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-menu-40.png")); // NOI18N
        jButton6.setText("VOTE IS OUR RIGHT");
        jButton6.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel1.add(jButton6);

        pnSide.add(jPanel1);

        jButton1.setForeground(new java.awt.Color(0, 255, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-home-25.png")); // NOI18N
        jButton1.setText(" HOME");
        jButton1.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnSide.add(jButton1);

        jButton2.setForeground(new java.awt.Color(0, 255, 204));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-elections-25.png")); // NOI18N
        jButton2.setText("VOTERS");
        jButton2.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnSide.add(jButton2);

        jButton3.setForeground(new java.awt.Color(0, 255, 204));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-people-25.png")); // NOI18N
        jButton3.setText("ADMINISTRATOR");
        jButton3.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnSide.add(jButton3);

        jButton4.setForeground(new java.awt.Color(0, 255, 204));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-leader-25.png")); // NOI18N
        jButton4.setText("CANDITATES");
        jButton4.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnSide.add(jButton4);

        jButton5.setForeground(new java.awt.Color(0, 255, 204));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-list-25.png")); // NOI18N
        jButton5.setText("VOTER LIST");
        jButton5.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        pnSide.add(jButton5);

        jButton7.setForeground(new java.awt.Color(0, 255, 204));
        jButton7.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-user-manual-25.png")); // NOI18N
        jButton7.setText("INSTRUCTIONS");
        jButton7.setPreferredSize(new java.awt.Dimension(200, 40));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pnSide.add(jButton7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnSide.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(34, 40, 44));
        jPanel6.setMinimumSize(new java.awt.Dimension(200, 280));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 280));

        jButton13.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-18-plus-100.png")); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 102));
        jLabel5.setText("IF YOU ARE ABOVE");

        jLabel6.setForeground(new java.awt.Color(255, 255, 102));
        jLabel6.setText("APPLY HERE FOR");

        jLabel7.setForeground(new java.awt.Color(255, 255, 102));
        jLabel7.setText("VOTER ID");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnSide.add(jPanel6);

        pnRoot.add(pnSide, java.awt.BorderLayout.WEST);

        pnCenter.setBackground(new java.awt.Color(34, 40, 44));
        pnCenter.setLayout(new java.awt.BorderLayout());

        pnCBottom.setBackground(new java.awt.Color(30, 40, 44));
        pnCBottom.setPreferredSize(new java.awt.Dimension(734, 100));

        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-location-40.png")); // NOI18N
        jLabel1.setText("PSG COLLEGE OF TECHNOLOGY");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\icons hub\\icons8-date-40.png")); // NOI18N
        jLabel3.setText("DATE : 11/11/2021");

        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Copyright © 2021 PSG. All rights reserved");

        javax.swing.GroupLayout pnCBottomLayout = new javax.swing.GroupLayout(pnCBottom);
        pnCBottom.setLayout(pnCBottomLayout);
        pnCBottomLayout.setHorizontalGroup(
            pnCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCBottomLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(105, 105, 105)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1146, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(176, 176, 176))
        );
        pnCBottomLayout.setVerticalGroup(
            pnCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCBottomLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(pnCBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23))
        );

        pnCenter.add(pnCBottom, java.awt.BorderLayout.SOUTH);

        pniCTop.setBackground(new java.awt.Color(34, 40, 44));
        pniCTop.setPreferredSize(new java.awt.Dimension(0, 150));

        jLabel2.setFont(new java.awt.Font("Adobe Caslon Pro", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Rules & Regulations");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 175, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pniCTopLayout = new javax.swing.GroupLayout(pniCTop);
        pniCTop.setLayout(pniCTopLayout);
        pniCTopLayout.setHorizontalGroup(
            pniCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pniCTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pniCTopLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1075, Short.MAX_VALUE)
                .addGroup(pniCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pniCTopLayout.setVerticalGroup(
            pniCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pniCTopLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pniCTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pniCTopLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(pniCTopLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnCenter.add(pniCTop, java.awt.BorderLayout.NORTH);

        pniCCenter.setBackground(new java.awt.Color(30, 40, 44));

        jLabel8.setFont(new java.awt.Font("Adobe Caslon Pro Bold", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 255, 102));
        jLabel8.setText("Follow These Instructions (Voters)");

        jTextArea1.setBackground(new java.awt.Color(0, 0, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("NOTIFICATION Regarding Election:-\n                       \n               Whereas, the Election Commission has announced the schedule for the General Elections to the Legislative Assemblies of Assam, Kerala, Tamil Nadu, West Bengal & Puducherryvide Press Note No ECI/PN/16/2021, dated 26th February, 2021.\n\n(1) Whereas, the Election Commission has announced the schedule for the bye-elections from 6-Malappuram Parliamentary Constituency of Kerala and 39-Kanniyakumari Parliamentary Constituency of Tamil Naduvide Press Note No. ECI/PN/17/2021 dated 26th February, 2021; and\nWhereas, the Election Commission has announced the schedule for the bye-elections from23-Tirupati(SC) Parliamentary Constituency of Andhra Pradesh & 2-Belgaum Parliamentary Constituency of Karnataka, 125-Morva Hadaf(ST) Assembly Constituency of Gujarat,  13-Madhupur Assembly Constituency of Jharkhand, 47-Basavakalyan & 59-Maski(ST) Assembly Constituencies of Karnataka, 55-Damoh Assembly Constituency of Madhya Pradesh,252-Pandharpur Assembly Constituency of Maharashtra, 26-Serchhip(ST)Assembly Constituency of Mizoram, 51-Noksen(ST) Assembly Constituency of Nagaland, 110-Pipili Assembly Constituency of Odisha, 179-Sahara,  24-Sujangarh(SC) & 175-Rajsamand Assembly Constituencies of Rajasthan, 87-Nagarjuna Sagar Assembly Constituency of Telangana and 49-Salt Assembly Constituency of Uttarakhandvide Press Note No. ECI/PN/28/2021 dated 16th March, 2021.\nAnd whereas, Section 126A of The Representation of the People Act, 1951(in short R.P. Act, 1951) specifies that“(1)No person shall conduct any exit poll and publish or publicise by means of the print or electronic media or disseminate in any other manner, whatsoever, the result of any exit poll during such period, as may be notified by the Election Commission in this regard.\n\n\n(2) For the purposes of sub-section (1), the Election Commission shall, by a general order, notify the date and time having due regard to the following, namely:—\n       (a) in case of a general election, the period may commence from the beginning of the hours fixed for poll on the first day of poll and continue till half an hour after closing of the poll in all the States and Union territories;\n             Provided that in case of a number of bye-elections held together on different days, the period may commence from the beginning of the hours fixed for poll on the first day of poll and continue till half an hour after closing of the last poll.\n\n\n(3) Any person who contravenes the provisions of this section shall be punishable with imprisonment for a term which may extend to two years or with fine or with both.”\nNow, therefore, in exercise of the powers under sub-Section (1) of Section 126A of the R.P. Act, 1951, the Election Commission, having regard to the provisions of sub-Section (2) of the said Section, hereby notifies the period between 7:00A.M on 27thMarch, 2021 (Saturday) and 7.30 PM on 29th April, 2021 (Thursday),as the period during which conducting any exit poll and publishing or publicizing by means of the print  or electronic media or dissemination in any other manner whatsoever, the result of any exit poll in connection with the aforesaid General Elections/ Bye-elections, shall be prohibited.\nIt is further clarified that under Section 126(1)(b) of the R.P. Act, 1951, displaying any election matter including results of any opinion poll or any other poll survey, in any electronic media, would be prohibited during the period of 48 hours ending with the hours fixed for conclusion of poll in the respective polling areas in connection with General elections and Bye elections.\n\n\n\nBye-Election:-\n\n1.No.576/3/EVM/2021/SDR-Vol.II:- Whereas, Section 61A of the Representation of the People Act, 1951, provides that the giving and recording of votes by Voting Machines in such manner as may be prescribed, may be adopted in such constituency or constituencies as the Election Commission of India may, having regard to the circumstances of each case, specify; and\n\n\n2.Whereas, as per the proviso to Rule 49A of the Conduct of Elections Rules, 1961, a Printer with a drop box of such design, as may be approved by the Election Commission of India, may also be attached to voting machine for printing a paper trail of the vote, in such constituency or constituencies or parts thereof as the Election Commission of India may direct; and\n\n\n3.Whereas, the Election Commission has considered the circumstances in 6-Malappuram Parliamentary Constituency of Kerala, 39-Kanniyakumari Parliamentary Constituency of Tamil Nadu 23-Tirupati(SC) Parliamentary Constituency of Andhra Pradesh & 2-Belgaum Parliamentary Constituency of Karnataka, 125-Morva Hadaf(ST) Assembly Constituency of Gujarat,  13-Madhupur Assembly Constituency of Jharkhand, 47-Basavakalyan &59-Maski(ST) Assembly Constituencies of Karnataka, 55-Damoh Assembly Constituency of Madhya Pradesh, 252-Pandharpur Assembly Constituency of Maharashtra, 26-Serchhip(ST) Assembly Constituency of Mizoram, 51-Noksen(ST) Assembly Constituency of Nagaland, 110-Pipili Assembly Constituency of Odisha,179-Sahara, 24-Sujangarh(SC) & 175-Rajsamand Assembly Constituencies of Rajasthan, 87-Nagarjuna Sagar Assembly Constituency of Telangana and 49-Salt Assembly Constituency of Uttarakhand,.announced vide the Election Commission’s Press Note No. ECI/PN/17/2021 dated 26thFebruary, 2021 and No. ECI/PN/28/2021 dated 16th March, 2021and is satisfied that sufficient number of Electronic Voting Machines (EVMs) and Printers for printing Paper Trail [Voter Verifiable Paper Audit Trail(VVPAT)] are available for taking the poll in above mentioned Parliamentary and Assembly Constituencies, the polling personnel are well trained in efficient handling of EVMs and ‘VVPAT Printers’ and the electors are also fully conversant with the operation of the EVMs and the VVPAT  Printers;\n\n\n4.Now, therefore, the Election Commission of India, in exercise of its powers under the said Section 61A of the Representation of the People Act, 1951, and Rule 49A of the Conduct of Elections Rules, 1961, hereby specifies 6-Malappuram Parliamentary Constituency of Kerala, 39-Kanniyakumari Parliamentary Constituency of Tamil Nadu 23-Tirupati(SC) Parliamentary Constituency of Andhra Pradesh & 2-Belgaum Parliamentary Constituency of Karnataka, 125-Morva Hadaf(ST) Assembly Constituency of Gujarat,  13-Madhupur Assembly Constituency of Jharkhand, 47-Basavakalyan &59-Maski(ST) Assembly Constituencies of Karnataka, 55-Damoh Assembly Constituency of Madhya Pradesh, 252-Pandharpur Assembly Constituency of Maharashtra, 26-Serchhip(ST) Assembly Constituency of Mizoram, 51-Noksen(ST) Assembly Constituency of Nagaland, 110-Pipili Assembly Constituency of Odisha, 179-Sahara,  24-Sujangarh(SC) & 175-Rajsamand Assembly Constituencies of Rajasthan, 87-Nagarjuna Sagar Assembly Constituency of Telangana and 49-Salt Assembly Constituency of Uttarakhand,.notifiedon 12-03-2021& 23-03-2021, as theconstituencies in which the votes,shall be given and recorded by means of EVMsand  VVPAT printers in the manner prescribed, under the Conduct of Elections Rules, 1961, and the supplementary instructions issued by the Election Commission from time to time on the subject.\n\n\n5.The Election Commission also hereby approves the design of EVMs and VVPAT Printers as developed by the Bharat Electronics Ltd., Bangalore and Electronics Corporation of India Ltd., Hyderabad, which shall be attached to the said machines, to be used for the giving and recording of votes in all the Constituencies.\n\n\n\nBye Elections to the House of the People of Kerala, Tamil Nadu, Andhra Pradesh & Karnataka and Legislative Assemblies of various states- Election Commission's order regarding identification of electors - regarding:-\n\n\n1.            Whereas, Section 61 of the Representation of the People Act, 1951 provides that with a view to preventing impersonation of electors, so as to make the right of genuine electors to vote under section 62 of that Act more effective, provisions may be made by rules under that Act for use of Electors Photo Identity Card for electors as the means of establishing their identity at the time of polling; and\n\n\n2.      Whereas, Rule 28 of the Registration of Electors Rules, 1960, empowers the Election Commission to direct, with a view to preventing impersonation of electors and facilitating their identification at the time of poll, the issue of Electors Photo Identity Card to electors bearing their photographs at State cost; and\n\n\n3.         Whereas, Rules 49H (3) and 49K (2) (b) of the Conduct of Elections Rules, 1961, stipulate that where the electors of a constituency have been supplied with Electors Photo Identity Card under the said provisions of Rule 28 of the Registration of Electors Rules, 1960, the electors shall produce their Electors Photo Identity Card at the polling station and failure or refusal on their part to produce those Electors Photo Identity Card may result in the denial of permission to vote; and\n\n\n4.         Whereas, a combined and harmonious reading of the aforesaid provisions of the said Act and the Rules, makes it clear that although the right to vote arises by the existence of the name in the electoral roll, it is also dependent upon the use of the Electors Photo Identity Card, where provided by the Election Commission at State cost, as the means of establishing their identity at the time of polling and that both are to be used together; and\n\n\n5.         Whereas, the Election Commission made an Order on the 28th August, 1993, directing the issue of Electors Photo Identity Card (EPIC) to all electors, according to a time bound programme; and\n\n\n6.        Whereas, Electors Photo Identity Card have been issued to approximate 100% electors in the State of Kerala,Tamil Nadu, Andhra Pradesh, Karnataka, Gujarat, Jharkhand, Madhya Pradesh, Maharashtra, Mizoram, Nagaland, Odisha, Rajasthan, Telangana & Uttarakhand and\n\n\n7.          Now, therefore, after taking into account all relevant factors and the legal and factual position, the Election Commission hereby directs that for the current bye-elections from 6-Malappuram Parliamentary Constituency of Kerala, 39-Kanniyakumari Parliamentary Constituency of Tamil Nadu 23-Tirupati(SC) Parliamentary Constituency of Andhra Pradesh & 2-Belgaum Parliamentary Constituency of Karnataka, 125-Morva Hadaf(ST) Assembly Constituency of Gujarat,  13-Madhupur Assembly Constituency of Jharkhand, 47-Basavakalyan & 59-Maski(ST) Assembly Constituencies of Karnataka, 55-Damoh Assembly Constituency of Madhya Pradesh, 252-Pandharpur Assembly Constituency of Maharashtra, 26-Serchhip(ST) Assembly Constituency of Mizoram, 51-Noksen(ST) Assembly Constituency of Nagaland, 110-Pipili Assembly Constituency of Odisha, 179-Sahara,  24-Sujangarh(SC) & 175-Rajsamand Assembly Constituencies of Rajasthan, 87-Nagarjuna Sagar Assembly Constituency of Telangana and 49-Salt Assembly Constituency of Uttarakhand notified on 12-03-2021& 23-03-2021, all electors who have been issued EPIC shall produce the EPIC for their identification at the polling station before casting their votes. Those electors who are not able to produce the EPIC shall produce one of the following alternative photo identity documents for establishing their identity: -\n(i) Aadhaar Card,\n\n(ii) MNREGA Job Card,\n\n(iii)Passbooks with photograph issued by Bank/Post Office,\n\n(iv) Health Insurance Smart Card issued under the scheme of Ministry of Labour,\n\n(v) Driving License,\n\n(vi) Pan Card,\n\n(vii) Smart Card issued by RGI under NPR,\n\n(viii) Indian Passport,\n\n(ix)  Pension document with photograph,\n\n(x)Service Identity Cards with photograph issued to employees by Central/State  Govt./PSUs/Public Limited Companies, and\n\n(xi)  Official identity cards issued to MPs/MLAs/MLCs.\n\n\n8.         In the case of EPIC, clerical errors, spelling mistakes, etc. should be ignored provided the identity of the elector can be established by the EPIC. If an elector produces an EPIC which has been issued by the Electoral Registration Officer of another Assembly Constituency, such EPIC shall also be accepted for identification provided the name of that elector finds place in the electoral roll pertaining to the polling station where the elector has turned up for voting. If it is not possible to establish the identity of the elector on account of mismatch of photograph, etc. the elector shall have to produce one of the alternative photo documents mentioned in Para 7 above.\n\n\n9.         Notwithstanding anything in Para 7 above, overseas electors who are registered in the electoral roll under Section 20A of the Representation of the People Act, 1950, based on the particulars in their Indian Passport, shall be identified on the basis of their original passport only (and no other identity document) in the polling station.");
        jTextArea1.setDisabledTextColor(new java.awt.Color(204, 0, 51));
        jTextArea1.setEnabled(false);
        jTextArea1.setSelectedTextColor(new java.awt.Color(255, 255, 153));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pniCCenterLayout = new javax.swing.GroupLayout(pniCCenter);
        pniCCenter.setLayout(pniCCenterLayout);
        pniCCenterLayout.setHorizontalGroup(
            pniCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pniCCenterLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pniCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(925, Short.MAX_VALUE))
        );
        pniCCenterLayout.setVerticalGroup(
            pniCCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pniCCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnCenter.add(pniCCenter, java.awt.BorderLayout.CENTER);

        pnRoot.add(pnCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnRoot, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        VotersList h = new VotersList();
        h.show();
        
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Home h = new Home();
        h.show();
        
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        VotersLogin h = new VotersLogin();
        h.show();
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        NewVoterApplication h = new NewVoterApplication();
        h.show();
        
        dispose();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        AdminLogin h = new AdminLogin();
        h.show();
        
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Canditates h = new Canditates();
        h.show();
        
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instructions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instructions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pnCBottom;
    private javax.swing.JPanel pnCenter;
    private javax.swing.JPanel pnRoot;
    private javax.swing.JPanel pnSide;
    private javax.swing.JPanel pniCCenter;
    private javax.swing.JPanel pniCTop;
    // End of variables declaration//GEN-END:variables
}
